import { db, productsTable, categoriesTable } from "@workspace/db";

const categories = [
  { name: "Smartphones", slug: "smartphones" },
  { name: "Accessories", slug: "accessories" },
  { name: "Plans", slug: "plans" },
  { name: "Tablets", slug: "tablets" },
];

const products = [
  {
    name: "iPhone 15 Pro",
    brand: "Apple",
    category: "smartphones",
    description: "The most powerful iPhone ever with the A17 Pro chip, titanium design, and USB 3 speeds.",
    price: 999,
    originalPrice: 1099,
    imageUrl: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400",
    inStock: true,
    featured: true,
    rating: 4.8,
    reviewCount: 1240,
    specs: JSON.stringify({ display: "6.1-inch Super Retina XDR", chip: "A17 Pro", storage: "256GB", camera: "48MP" }),
    badge: "Best Seller",
  },
  {
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    category: "smartphones",
    description: "Ultimate Android flagship with built-in S Pen, 200MP camera, and Snapdragon 8 Gen 3.",
    price: 1199,
    originalPrice: 1299,
    imageUrl: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400",
    inStock: true,
    featured: true,
    rating: 4.7,
    reviewCount: 980,
    specs: JSON.stringify({ display: "6.8-inch Dynamic AMOLED", chip: "Snapdragon 8 Gen 3", storage: "256GB", camera: "200MP" }),
    badge: "New",
  },
  {
    name: "Google Pixel 8 Pro",
    brand: "Google",
    category: "smartphones",
    description: "AI-powered photography and 7 years of OS updates with Google's Tensor G3 chip.",
    price: 899,
    originalPrice: 999,
    imageUrl: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400",
    inStock: true,
    featured: true,
    rating: 4.6,
    reviewCount: 720,
    specs: JSON.stringify({ display: "6.7-inch LTPO OLED", chip: "Tensor G3", storage: "128GB", camera: "50MP" }),
    badge: "Sale",
  },
  {
    name: "OnePlus 12",
    brand: "OnePlus",
    category: "smartphones",
    description: "Flagship killer with 100W charging, Hasselblad cameras, and silky-smooth 120Hz display.",
    price: 799,
    originalPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=400",
    inStock: true,
    featured: false,
    rating: 4.5,
    reviewCount: 540,
    specs: JSON.stringify({ display: "6.82-inch LTPO AMOLED", chip: "Snapdragon 8 Gen 3", storage: "256GB", camera: "50MP" }),
    badge: null,
  },
  {
    name: "iPhone 14",
    brand: "Apple",
    category: "smartphones",
    description: "Powerful performance and great camera system at a more accessible price.",
    price: 699,
    originalPrice: 799,
    imageUrl: "https://images.unsplash.com/photo-1663499482523-1c0c1bae4ce1?w=400",
    inStock: true,
    featured: false,
    rating: 4.5,
    reviewCount: 2100,
    specs: JSON.stringify({ display: "6.1-inch Super Retina XDR", chip: "A15 Bionic", storage: "128GB", camera: "12MP" }),
    badge: "Sale",
  },
  {
    name: "AirPods Pro 2nd Gen",
    brand: "Apple",
    category: "accessories",
    description: "Next-level Active Noise Cancellation, Transparency mode, and Adaptive Audio.",
    price: 249,
    originalPrice: 279,
    imageUrl: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=400",
    inStock: true,
    featured: true,
    rating: 4.8,
    reviewCount: 3200,
    specs: JSON.stringify({ type: "In-ear", anc: "Active Noise Cancellation", battery: "6h + 24h case", connectivity: "Bluetooth 5.3" }),
    badge: "Best Seller",
  },
  {
    name: "Samsung Galaxy Buds2 Pro",
    brand: "Samsung",
    category: "accessories",
    description: "Hi-Fi 24-bit audio, intelligent ANC, and seamless Galaxy ecosystem integration.",
    price: 179,
    originalPrice: 229,
    imageUrl: "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=400",
    inStock: true,
    featured: false,
    rating: 4.5,
    reviewCount: 890,
    specs: JSON.stringify({ type: "In-ear", anc: "Active Noise Cancellation", battery: "5h + 18h case", connectivity: "Bluetooth 5.3" }),
    badge: "Sale",
  },
  {
    name: "MagSafe Charger",
    brand: "Apple",
    category: "accessories",
    description: "Fast, easy, perfectly aligned wireless charging for iPhone 12 and later.",
    price: 39,
    originalPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?w=400",
    inStock: true,
    featured: false,
    rating: 4.6,
    reviewCount: 4100,
    specs: JSON.stringify({ type: "Wireless Charger", output: "15W", compatibility: "iPhone 12+", cable: "1m USB-C" }),
    badge: null,
  },
  {
    name: "Anker 65W GaN Charger",
    brand: "Anker",
    category: "accessories",
    description: "Compact 3-port charger with GaN technology charges your laptop, phone, and tablet at once.",
    price: 49,
    originalPrice: 59,
    imageUrl: "https://images.unsplash.com/photo-1583863788434-e62bd5f98bcc?w=400",
    inStock: true,
    featured: false,
    rating: 4.7,
    reviewCount: 6500,
    specs: JSON.stringify({ type: "Wall Charger", output: "65W", ports: "2x USB-C, 1x USB-A", technology: "GaN" }),
    badge: "Sale",
  },
  {
    name: "Unlimited Plus Plan",
    brand: "CellHub",
    category: "plans",
    description: "Truly unlimited data, talk, and text with 50GB of premium network access and hotspot.",
    price: 75,
    originalPrice: 90,
    imageUrl: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400",
    inStock: true,
    featured: true,
    rating: 4.4,
    reviewCount: 2800,
    specs: JSON.stringify({ data: "Unlimited", hotspot: "50GB", talk: "Unlimited", text: "Unlimited" }),
    badge: "Popular",
  },
  {
    name: "Starter Plan",
    brand: "CellHub",
    category: "plans",
    description: "5GB of data, unlimited talk and text. Perfect for light users on a budget.",
    price: 25,
    originalPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400",
    inStock: true,
    featured: false,
    rating: 4.2,
    reviewCount: 1200,
    specs: JSON.stringify({ data: "5GB", hotspot: "None", talk: "Unlimited", text: "Unlimited" }),
    badge: null,
  },
  {
    name: "iPad Air (M2)",
    brand: "Apple",
    category: "tablets",
    description: "Supercharged by M2, featuring a stunning Liquid Retina display and works with Apple Pencil Pro.",
    price: 599,
    originalPrice: 649,
    imageUrl: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400",
    inStock: true,
    featured: true,
    rating: 4.8,
    reviewCount: 860,
    specs: JSON.stringify({ display: "11-inch Liquid Retina", chip: "M2", storage: "128GB", camera: "12MP" }),
    badge: "New",
  },
];

async function seed() {
  console.log("Seeding categories...");
  await db.delete(categoriesTable);
  const insertedCategories = await db.insert(categoriesTable).values(categories).returning();
  console.log(`Inserted ${insertedCategories.length} categories`);

  console.log("Seeding products...");
  await db.delete(productsTable);
  const insertedProducts = await db.insert(productsTable).values(products).returning();
  console.log(`Inserted ${insertedProducts.length} products`);

  console.log("Done!");
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
